version: "3"

services:
  soft-arq-auth:
    build: .
    container_name: arq-soft-auth
    ports:
      - "8001:8001"
    networks:
      - default
      - puc-arq-soft
    environment:
      - PORT=8001
      - SECRET=SECRET
      - FAKE_STORE_API_URL=https://fakestoreapi.com/
      - DB_NAME=auth
      - ENV=$ENV
      - OTEL_SERVICE_NAME=puc-arq-soft-auth
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    volumes:
      - "./src:/app/src"
      - "./db:/app/db"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: requirements.txt

networks:
  puc-arq-soft:
    external: true
    name: puc-arq-soft-net
